NAME = Bureaucrat

SRCS =  main.cpp Bureaucrat.cpp   
OBJS = $(SRCS:.cpp=.o)

CXX = c++
CXXFLAGS =  -std=c++98

all: $(NAME)

$(NAME): $(OBJS) Bureaucrat.hpp
	$(CXX) $(CXXFLAGS) $(OBJS) -o $(NAME)

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re